import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'
import Providers from './components/Providers';
import logo from "./assets/favicon.png";

const satoshi = localFont({
  src: './fonts/Satoshi-Variable.ttf',
  variable: "--font-satoshi",
});

export const metadata = {
  title: "Count Down Timer",
  description: "Generated by Aaron Kurian Abraham and TinkerHub MEC",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href={logo.src} type="image/png" />
      </head>
      <body
        className={`${satoshi.variable} antialiased`}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
